doc: require main default branch before transfer
nodejs/admin pull request #550
Opened 2020-09-02 23:10 UTC by mmarchini

Our org default branch is set to `main`, so it makes sense 
to also require new repositories being transferred to the org
to follow the same pattern.

2020-09-02 23:30 UTC, mcollina requested changes
I'm -1. Not _yet_. The tools for supporting such a change are not really there yet from github own plan. From the last I read, everything should be done and feasible at the beginning of 2021.

Changing this is disruptive for projects.

2020-09-02 23:42 UTC, nschonni commented
This was the only thing I've seen for the timeline https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-
Don't know if it's that much of a bar for smaller repos transferring in vs. trying to do it on something large like nodjes/node

2020-09-02 23:46 UTC, ljharb commented
It seems reasonable to *suggest* it be changed first, but I do agree with @mcollina that until github's tools launch (redirecting all web links, and silently retargeting all PRs) it's not a low-cost change for some projects.

2020-09-03 00:00 UTC, mmarchini commented
> Changing this is disruptive for projects

Except for pull requests (which I agree), are there other ways this is disruptive to projects being transferred into the org? The redirect already exist, and I would expect any services _external_ to GitHub which rely on default branch to also rely on the org the project is in, which means those external services need to be updated anyway.

What do you think of:

> If possible, change the default branch to `main` before transferring the repository to the org.

2020-09-03 00:01 UTC, mcollina commented
I agree to have it as a suggestion. We can't ask for others to do what we are not ready to do ourselves (migrate nodejs/node, for the reasons mentioned above).

2020-09-03 00:05 UTC, ljharb commented
@mmarchini the current redirect works for links to a *deleted* branch, to the default branch, but not for every one of them. There are a number of links that still 404, from reports I've heard. Additionally, that doesn't work if you keep `master` as a protected branch (so nobody can push to it by accident); and any local tools that hardcode "master" instead of "HEAD" won't work, because there's no git-level redirecting being done (github does this on renamed/transferred repos; so i'm hoping they can do this on default branches too).

With "If possible," i see zero downsides, and it absolutely should be reevaluated as Github releases features to make this process more seamless.

2020-09-03 00:05 UTC, mmarchini commented
I don't think that's a fair comparison, projects being transferred to the foundation are _generally_ way less intertwined with extenral services, or widely referenced externally, or have 200+ open PRs or thousands of forks.

2020-09-03 00:07 UTC, mmarchini commented
@ljharb wasn't aware of those many caveats/edge cases and I definitely thought git-level redirect was working already. I don't mind keeping it as "if possible", so I'll update the PR.

2020-10-01 23:54 UTC, mmarchini commented
@mcollina updated the wording so it's a recommendation and not a requirement. Let me know what you think.

2020-10-08 20:52 UTC, mhdawson approved these changes
LGTM

2020-10-09 09:25 UTC, mcollina approved these changes
lgtm

2021-03-01 17:26 UTC, bitcoinworldhub commented
transfer-repo-into-the-org.md

2021-03-01 17:26 UTC, bitcoinworldhub commented
Our org default branch is set to main, so it makes sense
to also require new repositories being transferred to the org
to follow the same pattern.

2021-03-01 20:54 UTC, mhdawson approved these changes
LGTM

2021-03-02 07:31 UTC, targos approved these changes

2021-03-02 07:51 UTC, mmarchini commented
@nodejs/tsc @nodejs/community-committee fyi

2021-03-02 08:07 UTC, mcollina approved these changes
lgtm

2021-03-02 15:05 UTC, cjihrig approved these changes

2021-03-02 18:57 UTC, Trott approved these changes

2021-03-03 20:57 UTC, merged